"""empty message

Revision ID: 6c444ea99399
Revises: cf0c78e5b6c0
Create Date: 2019-09-01 13:35:30.527192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c444ea99399'
down_revision = 'cf0c78e5b6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_date_modified'), 'user', ['date_modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_date_modified'), table_name='user')
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.drop_column('user', 'date_modified')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
